version: '3.7'

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=freecodegram_development

volumes:
  dbdata: